from typing import Protocol, Sequence

from app.domain.entities import (
    AdminUser,
    Worker,
    Pair,
    Survey,
    Answer,
    Shift,
    Cabinet,
    Instrument,
    InstrumentMove,
)


class AdminRepository(Protocol):
    async def list_all(self) -> Sequence[AdminUser]: ...
    async def get_by_chat_id(self, chat_id: str) -> AdminUser | None: ...
    async def exists(self, chat_id: str) -> bool: ...
    async def add(self, admin: AdminUser) -> bool: ...
    async def delete_by_chat_id(self, chat_id: str) -> bool: ...


class WorkerRepository(Protocol):
    async def get_by_fullname(self, full_name: str) -> Worker | None: ...
    async def get_by_chat_id(self, chat_id: int) -> Worker | None: ...
    async def get_by_id(self, worker_id: int) -> Worker | None: ...
    async def list_all(self) -> Sequence[Worker]: ...
    async def list_unregistered(self) -> Sequence[Worker]: ...
    async def add(self, worker: Worker) -> None: ...
    async def set_chat_id(self, worker_id: int, chat_id: str) -> bool: ...
    async def set_file_id(self, worker_id: int, file_id: str) -> None: ...


class SurveyRepository(Protocol):
    async def get_by_name(self, name: str) -> Survey | None: ...
    async def clear_all(self) -> None: ...
    async def add(self, survey: Survey) -> None: ...


class PairRepository(Protocol):
    async def list_ready_by_date(self, date: str) -> Sequence[Pair]: ...
    async def next_ready_for_subject(self, subject: str) -> Pair | None: ...
    async def update_status(self, pair_id: int, status: str) -> None: ...
    async def reset_incomplete(self) -> None: ...
    async def add(self, pair: Pair) -> None: ...
    async def clear_all(self) -> None: ...


class AnswerRepository(Protocol):
    async def save(self, answer: Answer) -> None: ...
    async def list_all(self) -> Sequence[Answer]: ...


class ShiftRepository(Protocol):
    async def clear_all(self) -> None: ...
    async def bulk_insert(self, records: list[tuple[str, str, str]]) -> None: ...
    async def list_free(self, date: str, shift_type: str) -> list[tuple[int, str]]: ...
    async def get_by_id(self, shift_id: int) -> Shift | None: ...
    async def get_for_assistant(self, assistant_id: int, date: str, shift_type: str) -> Shift | None: ...
    async def remove_assistant(self, assistant_id: int, date: str, shift_type: str) -> None: ...
    async def add_by_id(self, assistant_id: int, assistant_name: str, shift_id: int) -> bool: ...
    async def add_manual(self, assistant_id: int, assistant_name: str, doctor_name: str, shift_type: str, date: str) -> bool: ...
    async def add_slot(self, doctor_name: str, date: str, shift_type: str) -> bool: ...
    async def delete_by_id(self, shift_id: int) -> bool: ...
    async def list_by_date(self, date: str) -> Sequence[Shift]: ...
    async def list_all(self) -> Sequence[Shift]: ...


class CabinetRepository(Protocol):
    async def list_all(self, include_archived: bool = False) -> Sequence[Cabinet]: ...
    async def get_by_id(self, cabinet_id: int) -> Cabinet | None: ...
    async def add(self, cabinet: Cabinet) -> None: ...
    async def update_name(self, cabinet_id: int, name: str) -> bool: ...
    async def set_active(self, cabinet_id: int, is_active: bool) -> bool: ...
    async def delete(self, cabinet_id: int) -> bool: ...
    async def has_instruments(self, cabinet_id: int) -> bool: ...


class InstrumentRepository(Protocol):
    async def list_by_cabinet(
        self, cabinet_id: int, include_archived: bool = False
    ) -> Sequence[Instrument]: ...
    async def get_by_id(self, instrument_id: int) -> Instrument | None: ...
    async def update_cabinet(self, instrument_id: int, cabinet_id: int) -> bool: ...
    async def add(self, instrument: Instrument) -> None: ...
    async def update_name(self, instrument_id: int, name: str) -> bool: ...
    async def set_active(self, instrument_id: int, is_active: bool) -> bool: ...
    async def delete(self, instrument_id: int) -> bool: ...


class InstrumentMoveRepository(Protocol):
    async def add(self, move: InstrumentMove) -> None: ...
    async def list_recent(self, limit: int = 20) -> Sequence[InstrumentMove]: ...
    async def get_by_id(self, move_id: int) -> InstrumentMove | None: ...
